version: '2'

services:
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
     - "28017:28017"
  homeconsole:
    environment:
      - HOMECONSOLE_SETTINGS=console_settings.py
    build: .
    command: flask run --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  homeserver:
    build: .
    command: python main.py --ssl --ssl-cert=certs/homeserver.crt.pem --ssl-key=certs/homeserver.key.pem --address=0.0.0.0 --port=2005
    volumes:
      - .:/code
    ports:
      - "2005:2005"
    depends_on:
      - mongodb
